# Generated by Django 4.2.3 on 2023-07-28 17:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_prestasi', models.CharField(blank=True, max_length=100, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.DateField(default=datetime.date(2023, 7, 28))),
                ('jam', models.CharField(choices=[(None, 'Pilih Jam Mengajar'), ('Jam ke-1', 'Jam ke-1 07.00 - 07.30 (Normal)'), ('Jam ke-2', 'Jam ke-2 07.30 - 08.10 (Normal)'), ('Jam ke-3', 'Jam ke-3 08.10 - 08.50 (Normal)'), ('Jam ke-4', 'Jam ke-4 08.55 - 09.35 (Normal)'), ('Jam ke-5', 'Jam ke-5 09.35 - 10.15 (Normal)'), ('Jam ke-6', 'Jam ke-6 10.45 - 11.25 (Normal)'), ('Jam ke-7', 'Jam ke-7 11.25 - 12.10 (Normal)'), ('Jam ke-8', 'Jam ke-8 13.40 - 14.20 (Normal)'), ('Jam ke-9', 'Jam ke-9 14.20 - 15.00 (Normal)')], max_length=50)),
                ('presensi', models.CharField(choices=[(None, 'Pilih Kehadiran'), ('Hadir', 'Hadir'), ('Sakit', 'Sakit'), ('Izin', 'Izin'), ('Alpha', 'Tanpa Keterangan')], default='Hadir', max_length=20)),
                ('keterangan', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='NilaiSikap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_spiritual', models.CharField(choices=[(None, 'Pilih Nilai Sikap'), ('A', 'Sangat Baik'), ('B', 'Baik'), ('C', 'Cukup'), ('D', 'Kurang Baik'), ('E', 'Buruk')], default='A', max_length=1)),
                ('nilai_sosial', models.CharField(choices=[(None, 'Pilih Nilai Sikap'), ('A', 'Sangat Baik'), ('B', 'Baik'), ('C', 'Cukup'), ('D', 'Kurang Baik'), ('E', 'Buruk')], default='A', max_length=1)),
                ('keterangan', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_nilai', models.CharField(max_length=10)),
                ('nilai', models.PositiveSmallIntegerField(default=0)),
                ('kategori_nilai', models.CharField(choices=[(None, 'Pilih Kategori Nilai'), ('Pengetahuan', 'Pengetahuan (Kognitif)'), ('Keterampilan', 'Keterampilan (Psikomotorik)')], max_length=20)),
                ('keterangan', models.CharField(blank=True, max_length=20, null=True)),
                ('tahun_ajaran', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.mengajar')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='Ekstrakurikuler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ekskul', models.CharField(blank=True, max_length=100, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='CatatanWalikelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catatan', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.siswa')),
            ],
        ),
    ]
