# Generated by Django 4.2.3 on 2023-07-28 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presensi',
            name='hari',
            field=models.DateField(default=datetime.date(2023, 7, 29)),
        ),
    ]
